### ISSUE TITLE
Add installation instructions & screenshot to README

### ISSUE THREAD

**Issue by maelle** [serrat839/mRkov_shiny#25]
I'm adding the link to this repo to R Weekly draft and was thinking it'd be nice to see the content of https://twitter.com/BryanDMartin_/status/1260723423468118017 in the README, as well as a screenshot of the app.

If you agree I'd use the screenshot of the app in R Weekly. https://github.com/rweekly/rweekly.org

**Comment by serrat839** [comment]
That sounds fantastic, thank you a ton! I’ll update the readme soon, I just need to get some other school work done.

**Comment by bryandmartin** [comment]
Hi @maelle ,

Is the current README what you are looking for? If so, I'll close the issue!

Thanks,
Bryan

**Comment by maelle** [comment]
yes, thank you!
